src/WebShop/ViewComponents/CartViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebShop.BLL;
using WebShop.Models.ShopModels;
using WebShop.Services;
using WebShop.ViewModels;

namespace WebShop.ViewComponents
{
    public class CartViewComponent : ViewComponent
    {
        private ProductsBusinessLayer _productsBL;
        private IFixerIO _fixerIOService;

        public CartViewComponent(ProductsBusinessLayer productsBL, IFixerIO fixerIOService)
        {
            _fixerIOService = fixerIOService;
            _productsBL = productsBL;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            decimal rate = await _fixerIOService.ReadRate();

            var cart = CartBL.GetCart(this.HttpContext);
            var count = await cart.GetCount();
            var priceSum = await cart.GetTotal();
            var cartLines = await cart.GetCartItems();
            
            List<CartLineViewModel> cartLineViewModel = new List<CartLineViewModel>();
            foreach (var cartLine in cartLines)
            {
                cartLineViewModel.Add(new CartLineViewModel
                {
                    CartLine = cartLine,
                    ProductName = _productsBL.GetLocalizedProductName(cartLine.Product),
                    LinePriceSum = cartLine.Product.ProductPrice * rate * cartLine.Quantity,
                    ProductPrice = cartLine.Product.ProductPrice * rate
                    
                });
            }
            CartLinesViewModel viewModel = new CartLinesViewModel
            {
                Quantity = count,
                TotalPrice = priceSum,
                CartLines = cartLineViewModel
            };

            return View(viewModel);
        }
    }
}

src/WebShop/ViewComponents/CategorySelectViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebShop.BLL;
using WebShop.Models.ShopModels;

namespace WebShop.ViewComponents
{
    public class CategorySelectViewComponent : ViewComponent
    {
        private ProductsBusinessLayer _productsBL;
        public CategorySelectViewComponent(ProductsBusinessLayer productsBL)
        {
            _productsBL = productsBL;
        }   
        public async Task<IViewComponentResult> InvokeAsync()
        {
            List<ProductCategory> categories =  await _productsBL.GetAllCategories();
            return View(categories);
        }
    }
}

src/WebShop/ViewComponents/LanguageSelectViewComponent.cs
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Options;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace WebShop.ViewComponents
{
    public class LanguageSelectViewComponent : ViewComponent
    {
        private IOptions<RequestLocalizationOptions> _locOptions;

        public LanguageSelectViewComponent(IOptions<RequestLocalizationOptions> locOptions)
        {
            _locOptions = locOptions;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var cultureItems = await _locOptions.Value.SupportedUICultures
                .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
                .ToAsyncEnumerable().ToList();

            return View((List<SelectListItem>)cultureItems);
        }



    }
}

src/WebShop/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebShop</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>




<body>


    <div class="navbar navbar-fixed-top">
        <div class="container">
            
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Products" asp-action="Index" class="navbar-brand">@Localizer["Products"]</a>
            </div>

            
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">

                    @*<li><a asp-area="" asp-controller="Products" asp-action="Index">@Localizer["Products"]</a></li>*@
                    <li><a asp-area="" asp-controller="ProductCategories" asp-action="Index">@Localizer["Categories"]</a></li>
                    <li><a asp-area="" asp-controller="Cart" asp-action="Index">@Localizer["ShoppingCart"]</a></li>
                    <li>@await Component.InvokeAsync("CategorySelect")</li>
                    <li id="cart-view-component">@await Component.InvokeAsync("Cart")</li>
                    <li>
                       
                    </li>
                </ul>
                <div class="pull-right">
                    @await Component.InvokeAsync("LanguageSelect")
                </div>
                @*@await Html.PartialAsync("_LoginPartial")*@
            </div>
        </div>
    </div>


    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <div class="row">
                <div class="col-md-6">
                    <p>&copy; 2016 - WebShop</p>
                </div>
                <div class="col-md-6 text-right">
                   @await Component.InvokeAsync("LanguageSelect")
                    @*@await Html.PartialAsync("_SelectLanguagePartial")*@
                </div>
            </div>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

src/WebShop/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http.Features
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    
    var cultureItems = LocOptions.Value.SupportedUICultures
        .Select(c => new SelectListItem { Value = c.Name, Text = c.DisplayName })
        .ToList();
}

<div title="@Localizer["Request culture provider:"] @requestCulture?.Provider?.GetType().Name">
    <form id="selectLanguage" asp-controller="Home" asp-action="SetLanguage" asp-route-returnUrl="@Context.Request.Path" method="post" class="form-horizontal" role="form">
        @Localizer["Language:"] <select name="culture" asp-for="@requestCulture.RequestCulture.UICulture.Name" asp-items="cultureItems"></select>
    </form>
</div>