src/WebShop/Models/ShopModels/Product.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
//using WebShop.Resources.Localization.Models.ShopModels;

namespace WebShop.Models.ShopModels
{
    public class Product
    {
        public int ProductId { get; set; }

        [DataType(DataType.Currency)]
        [Range(0.1, 1000000)]
        [Required]
        public decimal ProductPrice { get; set; }

        //[Required]
        //[DataType(DataType.Text)]
        //public string ProductItemNumber { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ProductImageUrl { get; set; }

        // Foreign key
        public int ProductCategoryId { get; set; }
        public ProductCategory ProductCategory { get; set; }

        [Required]
        public virtual ICollection<ProductTranslation> Translations { get; set; }

    }
}

src/WebShop/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using WebShop.Models.ShopModels;

namespace WebShop.ViewModels
{
    public class ProductViewModel
    {
        public int ProductId { get; set; }
        public int ProductCategoryId { get; set; }

        public ProductCategory ProductCategory { get; set; }

        [Display(Name = "ProductName", ResourceType = typeof(WebShop.Resources.Localization.Models.ShopModels.Product))] // , ResourceType = typeof(Resources.Localization.Models.ShopModels.Product)
        [MaxLength(30, ErrorMessage = "Max 30 characters long name")]
        [DataType(DataType.Text)]
        [Required(ErrorMessage = "Product name is required")]
        public string ProductName { get; set; }

        [Display(Name = "Description", ResourceType = typeof(WebShop.Resources.Localization.Models.ShopModels.Product))]
        [DataType(DataType.Text)]
        [MaxLength(100, ErrorMessage = "Max 100 characters long name")]
        //[RegularExpression(@"^[a-zåäöA-ZÅÄÖ\s]{1,40}$", ErrorMessage = "Only characters are allowed")]
        public string ProductDescription { get; set; }

        [Display(Name = "Price", ResourceType = typeof(WebShop.Resources.Localization.Models.ShopModels.Product))]
        [DataType(DataType.Currency)]
        [Range(0.1, 1000000, ErrorMessage = "Must be between 0.1 and 1000000")]
        [Required(ErrorMessage = "Price is required")]
        public decimal ProductPrice { get; set; }

        [DataType(DataType.ImageUrl)]
        public string ProductImageUrl { get; set; }
    }
}

src/WebShop/Controllers/WebShopControllers/ProductsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Threading.Tasks;
using WebShop.BLL;
using WebShop.ModelBinders;
using WebShop.Models.ShopModels;
using WebShop.Services;
using WebShop.ViewModels;

namespace WebShop.Controllers.WebShopControllers
{
    public class ProductsController : Controller
    {
        private ProductBL _productBL;
        private IFixerIO _fixerIOService;
        private decimal _rate;

        public ProductsController(ProductBL productBL, IFixerIO fixerIOService)
        {
            _productBL = productBL;
            _fixerIOService = fixerIOService;
        }

        // GET: Products
        public async Task<IActionResult> Index(string searchTerm, int? productCategoryId = null)
        {
            _rate = await _fixerIOService.ReadRate();

            var viewModel = await _productBL.GetAllProductsInCategory(productCategoryId);
            await SetPriceInViewModels(viewModel);

            if (string.IsNullOrEmpty(searchTerm))
                return View(viewModel);

            var searchResult = _productBL.SearchItemsByName(searchTerm, viewModel);
            return View(searchResult);
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
                return NotFound();

            ProductViewModel viewModel = await _productBL.GetSingleProductViewModel(id);

            if (viewModel == null)
                return NotFound();

            await SetPriceInViewModel(viewModel);
            return View(viewModel);
        }

        // GET: Products/Create
        [Authorize]
        //[Authorize(Roles ="Admin")]
        public IActionResult Create()
        {
            ViewData["ProductCategoryId"] = new SelectList(_productBL.ProductCategories, "ProductCategoryId", "ProductCategoryName");
            return View();
        }

        // POST: Products/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Create(ProductViewModel product)
        {
            if (ModelState.IsValid)
            {
                await _productBL.CreateProduct(product);
                return RedirectToAction("Index");
            }
            ViewData["ProductCategoryId"] = new SelectList(_productBL.ProductCategories, "ProductCategoryId", "ProductCategoryName", product.ProductCategoryId);
            return View(product);
        }

        // GET: Products/Edit/5
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
                return NotFound();

            ProductViewModel viewModel = await _productBL.GetSingleProductViewModel(id);

            if (viewModel == null)
                return NotFound();

            await SetPriceInViewModel(viewModel);
            ViewData["ProductCategoryId"] = new SelectList(_productBL.ProductCategories, "ProductCategoryId", "ProductCategoryName", viewModel.ProductCategoryId);
            return View(viewModel);
        }

        // POST: Products/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        //[Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductCategoryId,ProductDescription,ProductName,ProductPrice,ProductImageUrl")] ProductViewModel product)
        {
            if (id != product.ProductId)
                return NotFound($"id is {id}, product.ProductId is {product.ProductCategoryId}");

            if (ModelState.IsValid)
            {
                try
                {
                    await _productBL.Update(product);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                        return NotFound(id);
                    else
                        throw;
                }
                return RedirectToAction("Index");
            }
            ViewData["ProductCategoryId"] = new SelectList(_productBL.ProductCategories, "ProductCategoryId", "ProductCategoryName", product.ProductCategoryId);
            return View(product);
        }

        // GET: Products/Delete/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
                return NotFound();

            var product = await _productBL.GetSingleProductViewModel(id);

            if (product == null)
                return NotFound();

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _productBL.RemoveProduct(id);
            return RedirectToAction("Index");
        }

        private bool ProductExists(int id)
        {
            return _productBL.ProductExists(id);
        }
        private async Task SetPriceInViewModel(ProductViewModel viewModel)
        {
            var product = await _productBL.GetSingleModelItem(viewModel.ProductId);
            _rate = await _fixerIOService.ReadRate();
            viewModel.ProductPrice = _rate * product.ProductPrice;
        }
        private async Task SetPriceInViewModels(IEnumerable<ProductViewModel> viewModels)
        {
            _rate = await _fixerIOService.ReadRate();
            foreach (var vm in viewModels)
            {
                vm.ProductPrice = vm.ProductPrice * _rate;
            }
        }
    }
}

src/WebShop/Views/Products/Create.cshtml
@model WebShop.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<form asp-action="Create">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="ProductCategoryId" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <select asp-for="ProductCategoryId" class ="form-control" asp-items="ViewBag.ProductCategoryId"></select>
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductImageUrl" class="form-control" />
                <span asp-validation-for="ProductImageUrl" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebShop/Views/Products/Delete.cshtml
@model WebShop.ViewModels.ProductViewModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ProductDescription)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductDescription)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductPrice)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductPrice)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            <a asp-action="Index">Back to List</a>
        </div>
    </form>
</div>

src/WebShop/Views/Products/Details.cshtml
@model WebShop.ViewModels.ProductViewModel

@using Microsoft.AspNetCore.Mvc.Localization;
@inject IViewLocalizer Localizer;

@{
    ViewData["Title"] = "Details";
}
@{
    var returnPath = Context.Request.Path + Context.Request.QueryString;

}
<h2>@Html.DisplayFor(model => model.ProductName)</h2>

<div>
    <h4>@Html.DisplayFor(model => model.ProductDescription)</h4>
    <hr />
    <div class="row">
        <div class="col-md-6 pull-right">
            <img src=@Model.ProductImageUrl class="image-product-details">
        </div>
        <div class="col-md-5 text-left bg-info pull-right">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.ProductName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProductName)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ProductDescription)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProductDescription)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ProductPrice)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProductPrice)
                </dd>
                <dt>
                    @Html.DisplayNameFor(model => model.ProductCategory.ProductCategoryName)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.ProductCategory.ProductCategoryName)
                </dd>
                @*<dt>
                        @Html.DisplayNameFor(model => model.ProductImageUrl)
                    </dt>*@


            </dl>
            <form asp-action="AddToCart" asp-controller="Cart" asp-route-returnUrl="@returnPath" asp-route-id="@Model.ProductId" id="addToCartIndex">
                <div class="form-actions">
                    <input type="submit" value="@Localizer["Add to cart"]" class="btn btn-success" />
                </div>
            </form>
        </div>
    </div>
</div>
<div>
    <a asp-controller="Cart" asp-action="AddToCart" asp-route-id="@Model.ProductId" asp-route-returnUrl="@Context.Request.Path">Add to cart</a> |
    <a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |
    <a asp-action="Delete" asp-route-id="@Model.ProductId">@Localizer["Delete"]|</a>
    <a asp-action="Index">Back to List</a>
</div>

src/WebShop/Views/Products/Edit.cshtml
@model WebShop.ViewModels.ProductViewModel

@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


@{
    ViewData["Title"] = Localizer["Edit"];
}

<h2>@Localizer["PageHeader"]</h2>

<form asp-action="Edit">
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>

    <input type="hidden" asp-for="ProductId" />
        <div class="form-group">
            <label asp-for="ProductCategoryId" class="control-label col-md-2"></label>
            <div class="col-md-10">
                <select asp-for="ProductCategoryId" class="form-control" asp-items="ViewBag.ProductCategoryId"></select>
                <span asp-validation-for="ProductCategoryId" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductDescription" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductDescription" class="form-control" />
                <span asp-validation-for="ProductDescription" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductName" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductName" class="form-control" />
                <span asp-validation-for="ProductName" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductPrice" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductPrice" class="form-control" />
                <span asp-validation-for="ProductPrice" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <label asp-for="ProductImageUrl" class="col-md-2 control-label"></label>
            <div class="col-md-10">
                <input asp-for="ProductImageUrl" class="form-control" />
                <span asp-validation-for="ProductImageUrl" class="text-danger" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default"/>
            </div>
        </div>
    </div>
</form>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

src/WebShop/Views/Products/Index.cshtml
@using Microsoft.AspNetCore.Mvc.Localization

@inject IViewLocalizer Localizer

@model IEnumerable<WebShop.ViewModels.ProductViewModel>

@{
    ViewData["Title"] = Localizer["Title"];
    var returnPath = Context.Request.Path + Context.Request.QueryString;
}

<h2>@Localizer["PageHeader"]</h2>
<h3>@ViewData["test"]</h3>
    <form asp-controller="Products" asp-action="Index" method="get">
        <p>
            @Localizer["Product name:"] <input type = "text" name = "searchTerm" >
            <input type = "submit" value = "@Localizer["search"]" />
        </p>
        @*<select asp-for=@ViewBag.SelectedCategory class="form-control" asp-items="ViewBag.ProductCategoryId"></select>*@

    </form >

<div class="row product-boxes">

    @foreach (var item in Model)
    {
        <div class="col-md-3 col-xs-6 product-box">
            <a asp-action="Details" asp-route-id="@item.ProductId">
                <img src=@item.ProductImageUrl class="product-image">

                <div class="product-text-box">
                    <p>@Html.DisplayFor(modelItem => item.ProductName)</p>
                    <p>@Html.DisplayFor(modelItem => item.ProductPrice)</p>
                    <p>@Html.DisplayFor(modelItem => item.ProductDescription)</p>
                </div>
            </a>
                <form asp-action="AddToCart" asp-controller="Cart" asp-route-returnUrl="@returnPath" asp-route-id="@item.ProductId" id="addToCartIndex">
                    <div class="form-actions">
                        <input type="submit" value="@Localizer["Add to cart"]" class="btn btn-success" />
                    </div>
                </form>
                @*<a asp-action="AddToCart" asp-controller="Cart" asp-route-returnUrl="@Context.Request.Path" asp-route-id="@item.ProductId" id="addToCartIndex">@Localizer["Add to cart"]</a>*@

                @*<p>
                    <a asp-action="Edit" asp-route-id="@item.ProductId">@Localizer["Edit"]</a> |
                    <a asp-action="Details" asp-route-id="@item.ProductId">@Localizer["Details"]</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProductId">@Localizer["Delete"]</a>
                </p>*@
</div>

    }
</div>

@*<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ProductName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductDescription)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ProductPrice)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductDescription)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductPrice)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ProductId">@Localizer["Edit"]</a> |
                <a asp-action="Details" asp-route-id="@item.ProductId">@Localizer["Details"]</a> |
                <a asp-action="Delete" asp-route-id="@item.ProductId">@Localizer["Delete"]</a>
            </td>
        </tr>
}
    </tbody>
</table>*@
<p>
    <a asp-action="Create">@Localizer["Create New"]</a>
    @*<input asp-action="Create" class="btn btn-danger" type="button" value="@Localizer["Create New"]"/>*@
</p>